import Head from "next/head";

import Galery from "../component/general/galery/galery";
import Header from "../component/index/header/header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Galery />
    </div>
  );
}
